server:
  port: 8082

spring:
  datasource:
    password: stackuf
    url: jdbc:postgresql://localhost:5432/postgres
    username: stackuf
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
      show-sql: true
